// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// S3configsColumns holds the columns for the "s3configs" table.
	S3configsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "endpoint", Type: field.TypeString, Nullable: true},
		{Name: "access_key_id", Type: field.TypeString},
		{Name: "secret_access_key", Type: field.TypeString},
		{Name: "region", Type: field.TypeString},
		{Name: "bucket", Type: field.TypeString},
		{Name: "storage_s3_config", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// S3configsTable holds the schema information for the "s3configs" table.
	S3configsTable = &schema.Table{
		Name:       "s3configs",
		Columns:    S3configsColumns,
		PrimaryKey: []*schema.Column{S3configsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "s3configs_storages_s3_config",
				Columns:    []*schema.Column{S3configsColumns[6]},
				RefColumns: []*schema.Column{StoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// StoragesColumns holds the columns for the "storages" table.
	StoragesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"webdav", "s3"}},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// StoragesTable holds the schema information for the "storages" table.
	StoragesTable = &schema.Table{
		Name:       "storages",
		Columns:    StoragesColumns,
		PrimaryKey: []*schema.Column{StoragesColumns[0]},
	}
	// SyncJobsColumns holds the columns for the "sync_jobs" table.
	SyncJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "completed", "failed"}},
		{Name: "operation", Type: field.TypeEnum, Enums: []string{"backup", "restore"}},
		{Name: "message", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "completed_at", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "storage_sync_jobs", Type: field.TypeInt, Nullable: true},
	}
	// SyncJobsTable holds the schema information for the "sync_jobs" table.
	SyncJobsTable = &schema.Table{
		Name:       "sync_jobs",
		Columns:    SyncJobsColumns,
		PrimaryKey: []*schema.Column{SyncJobsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sync_jobs_storages_sync_jobs",
				Columns:    []*schema.Column{SyncJobsColumns[7]},
				RefColumns: []*schema.Column{StoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "is_admin", Type: field.TypeBool, Default: false},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// WebDavConfigsColumns holds the columns for the "web_dav_configs" table.
	WebDavConfigsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString},
		{Name: "username", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
		{Name: "storage_webdav_config", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// WebDavConfigsTable holds the schema information for the "web_dav_configs" table.
	WebDavConfigsTable = &schema.Table{
		Name:       "web_dav_configs",
		Columns:    WebDavConfigsColumns,
		PrimaryKey: []*schema.Column{WebDavConfigsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "web_dav_configs_storages_webdav_config",
				Columns:    []*schema.Column{WebDavConfigsColumns[4]},
				RefColumns: []*schema.Column{StoragesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		S3configsTable,
		StoragesTable,
		SyncJobsTable,
		UsersTable,
		WebDavConfigsTable,
	}
)

func init() {
	S3configsTable.ForeignKeys[0].RefTable = StoragesTable
	SyncJobsTable.ForeignKeys[0].RefTable = StoragesTable
	WebDavConfigsTable.ForeignKeys[0].RefTable = StoragesTable
}
