// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ca-x/vaultwarden-syncer/ent/s3config"
	"github.com/ca-x/vaultwarden-syncer/ent/storage"
	"github.com/ca-x/vaultwarden-syncer/ent/webdavconfig"
)

// Storage is the model entity for the Storage schema.
type Storage struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type storage.Type `json:"type,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StorageQuery when eager-loading is set.
	Edges        StorageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StorageEdges holds the relations/edges for other nodes in the graph.
type StorageEdges struct {
	// SyncJobs holds the value of the sync_jobs edge.
	SyncJobs []*SyncJob `json:"sync_jobs,omitempty"`
	// WebdavConfig holds the value of the webdav_config edge.
	WebdavConfig *WebDAVConfig `json:"webdav_config,omitempty"`
	// S3Config holds the value of the s3_config edge.
	S3Config *S3Config `json:"s3_config,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// SyncJobsOrErr returns the SyncJobs value or an error if the edge
// was not loaded in eager-loading.
func (e StorageEdges) SyncJobsOrErr() ([]*SyncJob, error) {
	if e.loadedTypes[0] {
		return e.SyncJobs, nil
	}
	return nil, &NotLoadedError{edge: "sync_jobs"}
}

// WebdavConfigOrErr returns the WebdavConfig value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StorageEdges) WebdavConfigOrErr() (*WebDAVConfig, error) {
	if e.WebdavConfig != nil {
		return e.WebdavConfig, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: webdavconfig.Label}
	}
	return nil, &NotLoadedError{edge: "webdav_config"}
}

// S3ConfigOrErr returns the S3Config value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StorageEdges) S3ConfigOrErr() (*S3Config, error) {
	if e.S3Config != nil {
		return e.S3Config, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: s3config.Label}
	}
	return nil, &NotLoadedError{edge: "s3_config"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Storage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case storage.FieldEnabled:
			values[i] = new(sql.NullBool)
		case storage.FieldID:
			values[i] = new(sql.NullInt64)
		case storage.FieldName, storage.FieldType:
			values[i] = new(sql.NullString)
		case storage.FieldCreatedAt, storage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Storage fields.
func (s *Storage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case storage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			s.ID = int(value.Int64)
		case storage.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				s.Name = value.String
			}
		case storage.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				s.Type = storage.Type(value.String)
			}
		case storage.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				s.Enabled = value.Bool
			}
		case storage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				s.CreatedAt = value.Time
			}
		case storage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				s.UpdatedAt = value.Time
			}
		default:
			s.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Storage.
// This includes values selected through modifiers, order, etc.
func (s *Storage) Value(name string) (ent.Value, error) {
	return s.selectValues.Get(name)
}

// QuerySyncJobs queries the "sync_jobs" edge of the Storage entity.
func (s *Storage) QuerySyncJobs() *SyncJobQuery {
	return NewStorageClient(s.config).QuerySyncJobs(s)
}

// QueryWebdavConfig queries the "webdav_config" edge of the Storage entity.
func (s *Storage) QueryWebdavConfig() *WebDAVConfigQuery {
	return NewStorageClient(s.config).QueryWebdavConfig(s)
}

// QueryS3Config queries the "s3_config" edge of the Storage entity.
func (s *Storage) QueryS3Config() *S3ConfigQuery {
	return NewStorageClient(s.config).QueryS3Config(s)
}

// Update returns a builder for updating this Storage.
// Note that you need to call Storage.Unwrap() before calling this method if this Storage
// was returned from a transaction, and the transaction was committed or rolled back.
func (s *Storage) Update() *StorageUpdateOne {
	return NewStorageClient(s.config).UpdateOne(s)
}

// Unwrap unwraps the Storage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (s *Storage) Unwrap() *Storage {
	_tx, ok := s.config.driver.(*txDriver)
	if !ok {
		panic("ent: Storage is not a transactional entity")
	}
	s.config.driver = _tx.drv
	return s
}

// String implements the fmt.Stringer.
func (s *Storage) String() string {
	var builder strings.Builder
	builder.WriteString("Storage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", s.ID))
	builder.WriteString("name=")
	builder.WriteString(s.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", s.Type))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", s.Enabled))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(s.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(s.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Storages is a parsable slice of Storage.
type Storages []*Storage
