// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/vaultwarden-syncer/ent/predicate"
	"github.com/ca-x/vaultwarden-syncer/ent/storage"
	"github.com/ca-x/vaultwarden-syncer/ent/syncjob"
)

// SyncJobQuery is the builder for querying SyncJob entities.
type SyncJobQuery struct {
	config
	ctx         *QueryContext
	order       []syncjob.OrderOption
	inters      []Interceptor
	predicates  []predicate.SyncJob
	withStorage *StorageQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SyncJobQuery builder.
func (sjq *SyncJobQuery) Where(ps ...predicate.SyncJob) *SyncJobQuery {
	sjq.predicates = append(sjq.predicates, ps...)
	return sjq
}

// Limit the number of records to be returned by this query.
func (sjq *SyncJobQuery) Limit(limit int) *SyncJobQuery {
	sjq.ctx.Limit = &limit
	return sjq
}

// Offset to start from.
func (sjq *SyncJobQuery) Offset(offset int) *SyncJobQuery {
	sjq.ctx.Offset = &offset
	return sjq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sjq *SyncJobQuery) Unique(unique bool) *SyncJobQuery {
	sjq.ctx.Unique = &unique
	return sjq
}

// Order specifies how the records should be ordered.
func (sjq *SyncJobQuery) Order(o ...syncjob.OrderOption) *SyncJobQuery {
	sjq.order = append(sjq.order, o...)
	return sjq
}

// QueryStorage chains the current query on the "storage" edge.
func (sjq *SyncJobQuery) QueryStorage() *StorageQuery {
	query := (&StorageClient{config: sjq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sjq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sjq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(syncjob.Table, syncjob.FieldID, selector),
			sqlgraph.To(storage.Table, storage.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, syncjob.StorageTable, syncjob.StorageColumn),
		)
		fromU = sqlgraph.SetNeighbors(sjq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SyncJob entity from the query.
// Returns a *NotFoundError when no SyncJob was found.
func (sjq *SyncJobQuery) First(ctx context.Context) (*SyncJob, error) {
	nodes, err := sjq.Limit(1).All(setContextOp(ctx, sjq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{syncjob.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sjq *SyncJobQuery) FirstX(ctx context.Context) *SyncJob {
	node, err := sjq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SyncJob ID from the query.
// Returns a *NotFoundError when no SyncJob ID was found.
func (sjq *SyncJobQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sjq.Limit(1).IDs(setContextOp(ctx, sjq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{syncjob.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sjq *SyncJobQuery) FirstIDX(ctx context.Context) int {
	id, err := sjq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SyncJob entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SyncJob entity is found.
// Returns a *NotFoundError when no SyncJob entities are found.
func (sjq *SyncJobQuery) Only(ctx context.Context) (*SyncJob, error) {
	nodes, err := sjq.Limit(2).All(setContextOp(ctx, sjq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{syncjob.Label}
	default:
		return nil, &NotSingularError{syncjob.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sjq *SyncJobQuery) OnlyX(ctx context.Context) *SyncJob {
	node, err := sjq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SyncJob ID in the query.
// Returns a *NotSingularError when more than one SyncJob ID is found.
// Returns a *NotFoundError when no entities are found.
func (sjq *SyncJobQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sjq.Limit(2).IDs(setContextOp(ctx, sjq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{syncjob.Label}
	default:
		err = &NotSingularError{syncjob.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sjq *SyncJobQuery) OnlyIDX(ctx context.Context) int {
	id, err := sjq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SyncJobs.
func (sjq *SyncJobQuery) All(ctx context.Context) ([]*SyncJob, error) {
	ctx = setContextOp(ctx, sjq.ctx, ent.OpQueryAll)
	if err := sjq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SyncJob, *SyncJobQuery]()
	return withInterceptors[[]*SyncJob](ctx, sjq, qr, sjq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sjq *SyncJobQuery) AllX(ctx context.Context) []*SyncJob {
	nodes, err := sjq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SyncJob IDs.
func (sjq *SyncJobQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sjq.ctx.Unique == nil && sjq.path != nil {
		sjq.Unique(true)
	}
	ctx = setContextOp(ctx, sjq.ctx, ent.OpQueryIDs)
	if err = sjq.Select(syncjob.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sjq *SyncJobQuery) IDsX(ctx context.Context) []int {
	ids, err := sjq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sjq *SyncJobQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sjq.ctx, ent.OpQueryCount)
	if err := sjq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sjq, querierCount[*SyncJobQuery](), sjq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sjq *SyncJobQuery) CountX(ctx context.Context) int {
	count, err := sjq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sjq *SyncJobQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sjq.ctx, ent.OpQueryExist)
	switch _, err := sjq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sjq *SyncJobQuery) ExistX(ctx context.Context) bool {
	exist, err := sjq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SyncJobQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sjq *SyncJobQuery) Clone() *SyncJobQuery {
	if sjq == nil {
		return nil
	}
	return &SyncJobQuery{
		config:      sjq.config,
		ctx:         sjq.ctx.Clone(),
		order:       append([]syncjob.OrderOption{}, sjq.order...),
		inters:      append([]Interceptor{}, sjq.inters...),
		predicates:  append([]predicate.SyncJob{}, sjq.predicates...),
		withStorage: sjq.withStorage.Clone(),
		// clone intermediate query.
		sql:  sjq.sql.Clone(),
		path: sjq.path,
	}
}

// WithStorage tells the query-builder to eager-load the nodes that are connected to
// the "storage" edge. The optional arguments are used to configure the query builder of the edge.
func (sjq *SyncJobQuery) WithStorage(opts ...func(*StorageQuery)) *SyncJobQuery {
	query := (&StorageClient{config: sjq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sjq.withStorage = query
	return sjq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Status syncjob.Status `json:"status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SyncJob.Query().
//		GroupBy(syncjob.FieldStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sjq *SyncJobQuery) GroupBy(field string, fields ...string) *SyncJobGroupBy {
	sjq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SyncJobGroupBy{build: sjq}
	grbuild.flds = &sjq.ctx.Fields
	grbuild.label = syncjob.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Status syncjob.Status `json:"status,omitempty"`
//	}
//
//	client.SyncJob.Query().
//		Select(syncjob.FieldStatus).
//		Scan(ctx, &v)
func (sjq *SyncJobQuery) Select(fields ...string) *SyncJobSelect {
	sjq.ctx.Fields = append(sjq.ctx.Fields, fields...)
	sbuild := &SyncJobSelect{SyncJobQuery: sjq}
	sbuild.label = syncjob.Label
	sbuild.flds, sbuild.scan = &sjq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SyncJobSelect configured with the given aggregations.
func (sjq *SyncJobQuery) Aggregate(fns ...AggregateFunc) *SyncJobSelect {
	return sjq.Select().Aggregate(fns...)
}

func (sjq *SyncJobQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sjq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sjq); err != nil {
				return err
			}
		}
	}
	for _, f := range sjq.ctx.Fields {
		if !syncjob.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sjq.path != nil {
		prev, err := sjq.path(ctx)
		if err != nil {
			return err
		}
		sjq.sql = prev
	}
	return nil
}

func (sjq *SyncJobQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SyncJob, error) {
	var (
		nodes       = []*SyncJob{}
		withFKs     = sjq.withFKs
		_spec       = sjq.querySpec()
		loadedTypes = [1]bool{
			sjq.withStorage != nil,
		}
	)
	if sjq.withStorage != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, syncjob.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SyncJob).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SyncJob{config: sjq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sjq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sjq.withStorage; query != nil {
		if err := sjq.loadStorage(ctx, query, nodes, nil,
			func(n *SyncJob, e *Storage) { n.Edges.Storage = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sjq *SyncJobQuery) loadStorage(ctx context.Context, query *StorageQuery, nodes []*SyncJob, init func(*SyncJob), assign func(*SyncJob, *Storage)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SyncJob)
	for i := range nodes {
		if nodes[i].storage_sync_jobs == nil {
			continue
		}
		fk := *nodes[i].storage_sync_jobs
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(storage.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "storage_sync_jobs" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sjq *SyncJobQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sjq.querySpec()
	_spec.Node.Columns = sjq.ctx.Fields
	if len(sjq.ctx.Fields) > 0 {
		_spec.Unique = sjq.ctx.Unique != nil && *sjq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sjq.driver, _spec)
}

func (sjq *SyncJobQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(syncjob.Table, syncjob.Columns, sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeInt))
	_spec.From = sjq.sql
	if unique := sjq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sjq.path != nil {
		_spec.Unique = true
	}
	if fields := sjq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, syncjob.FieldID)
		for i := range fields {
			if fields[i] != syncjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sjq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sjq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sjq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sjq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sjq *SyncJobQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sjq.driver.Dialect())
	t1 := builder.Table(syncjob.Table)
	columns := sjq.ctx.Fields
	if len(columns) == 0 {
		columns = syncjob.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sjq.sql != nil {
		selector = sjq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sjq.ctx.Unique != nil && *sjq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sjq.predicates {
		p(selector)
	}
	for _, p := range sjq.order {
		p(selector)
	}
	if offset := sjq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sjq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SyncJobGroupBy is the group-by builder for SyncJob entities.
type SyncJobGroupBy struct {
	selector
	build *SyncJobQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sjgb *SyncJobGroupBy) Aggregate(fns ...AggregateFunc) *SyncJobGroupBy {
	sjgb.fns = append(sjgb.fns, fns...)
	return sjgb
}

// Scan applies the selector query and scans the result into the given value.
func (sjgb *SyncJobGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sjgb.build.ctx, ent.OpQueryGroupBy)
	if err := sjgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SyncJobQuery, *SyncJobGroupBy](ctx, sjgb.build, sjgb, sjgb.build.inters, v)
}

func (sjgb *SyncJobGroupBy) sqlScan(ctx context.Context, root *SyncJobQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sjgb.fns))
	for _, fn := range sjgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sjgb.flds)+len(sjgb.fns))
		for _, f := range *sjgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sjgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sjgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SyncJobSelect is the builder for selecting fields of SyncJob entities.
type SyncJobSelect struct {
	*SyncJobQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sjs *SyncJobSelect) Aggregate(fns ...AggregateFunc) *SyncJobSelect {
	sjs.fns = append(sjs.fns, fns...)
	return sjs
}

// Scan applies the selector query and scans the result into the given value.
func (sjs *SyncJobSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sjs.ctx, ent.OpQuerySelect)
	if err := sjs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SyncJobQuery, *SyncJobSelect](ctx, sjs.SyncJobQuery, sjs, sjs.inters, v)
}

func (sjs *SyncJobSelect) sqlScan(ctx context.Context, root *SyncJobQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sjs.fns))
	for _, fn := range sjs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sjs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sjs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
