// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/vaultwarden-syncer/ent/storage"
	"github.com/ca-x/vaultwarden-syncer/ent/syncjob"
)

// SyncJobCreate is the builder for creating a SyncJob entity.
type SyncJobCreate struct {
	config
	mutation *SyncJobMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *SyncJobCreate) SetStatus(v syncjob.Status) *SyncJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetOperation sets the "operation" field.
func (_c *SyncJobCreate) SetOperation(v syncjob.Operation) *SyncJobCreate {
	_c.mutation.SetOperation(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *SyncJobCreate) SetMessage(v string) *SyncJobCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableMessage(v *string) *SyncJobCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *SyncJobCreate) SetStartedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableStartedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *SyncJobCreate) SetCompletedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableCompletedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SyncJobCreate) SetCreatedAt(v time.Time) *SyncJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SyncJobCreate) SetNillableCreatedAt(v *time.Time) *SyncJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetStorageID sets the "storage" edge to the Storage entity by ID.
func (_c *SyncJobCreate) SetStorageID(id int) *SyncJobCreate {
	_c.mutation.SetStorageID(id)
	return _c
}

// SetNillableStorageID sets the "storage" edge to the Storage entity by ID if the given value is not nil.
func (_c *SyncJobCreate) SetNillableStorageID(id *int) *SyncJobCreate {
	if id != nil {
		_c = _c.SetStorageID(*id)
	}
	return _c
}

// SetStorage sets the "storage" edge to the Storage entity.
func (_c *SyncJobCreate) SetStorage(v *Storage) *SyncJobCreate {
	return _c.SetStorageID(v.ID)
}

// Mutation returns the SyncJobMutation object of the builder.
func (_c *SyncJobCreate) Mutation() *SyncJobMutation {
	return _c.mutation
}

// Save creates the SyncJob in the database.
func (_c *SyncJobCreate) Save(ctx context.Context) (*SyncJob, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SyncJobCreate) SaveX(ctx context.Context) *SyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SyncJobCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := syncjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SyncJobCreate) check() error {
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SyncJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := syncjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SyncJob.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Operation(); !ok {
		return &ValidationError{Name: "operation", err: errors.New(`ent: missing required field "SyncJob.operation"`)}
	}
	if v, ok := _c.mutation.Operation(); ok {
		if err := syncjob.OperationValidator(v); err != nil {
			return &ValidationError{Name: "operation", err: fmt.Errorf(`ent: validator failed for field "SyncJob.operation": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SyncJob.created_at"`)}
	}
	return nil
}

func (_c *SyncJobCreate) sqlSave(ctx context.Context) (*SyncJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SyncJobCreate) createSpec() (*SyncJob, *sqlgraph.CreateSpec) {
	var (
		_node = &SyncJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(syncjob.Table, sqlgraph.NewFieldSpec(syncjob.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(syncjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Operation(); ok {
		_spec.SetField(syncjob.FieldOperation, field.TypeEnum, value)
		_node.Operation = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(syncjob.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(syncjob.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(syncjob.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(syncjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.StorageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   syncjob.StorageTable,
			Columns: []string{syncjob.StorageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(storage.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.storage_sync_jobs = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SyncJobCreateBulk is the builder for creating many SyncJob entities in bulk.
type SyncJobCreateBulk struct {
	config
	err      error
	builders []*SyncJobCreate
}

// Save creates the SyncJob entities in the database.
func (_c *SyncJobCreateBulk) Save(ctx context.Context) ([]*SyncJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SyncJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SyncJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SyncJobCreateBulk) SaveX(ctx context.Context) []*SyncJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SyncJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SyncJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
