// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ca-x/vaultwarden-syncer/ent/predicate"
	"github.com/ca-x/vaultwarden-syncer/ent/storage"
	"github.com/ca-x/vaultwarden-syncer/ent/webdavconfig"
)

// WebDAVConfigQuery is the builder for querying WebDAVConfig entities.
type WebDAVConfigQuery struct {
	config
	ctx         *QueryContext
	order       []webdavconfig.OrderOption
	inters      []Interceptor
	predicates  []predicate.WebDAVConfig
	withStorage *StorageQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WebDAVConfigQuery builder.
func (wdcq *WebDAVConfigQuery) Where(ps ...predicate.WebDAVConfig) *WebDAVConfigQuery {
	wdcq.predicates = append(wdcq.predicates, ps...)
	return wdcq
}

// Limit the number of records to be returned by this query.
func (wdcq *WebDAVConfigQuery) Limit(limit int) *WebDAVConfigQuery {
	wdcq.ctx.Limit = &limit
	return wdcq
}

// Offset to start from.
func (wdcq *WebDAVConfigQuery) Offset(offset int) *WebDAVConfigQuery {
	wdcq.ctx.Offset = &offset
	return wdcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wdcq *WebDAVConfigQuery) Unique(unique bool) *WebDAVConfigQuery {
	wdcq.ctx.Unique = &unique
	return wdcq
}

// Order specifies how the records should be ordered.
func (wdcq *WebDAVConfigQuery) Order(o ...webdavconfig.OrderOption) *WebDAVConfigQuery {
	wdcq.order = append(wdcq.order, o...)
	return wdcq
}

// QueryStorage chains the current query on the "storage" edge.
func (wdcq *WebDAVConfigQuery) QueryStorage() *StorageQuery {
	query := (&StorageClient{config: wdcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wdcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wdcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(webdavconfig.Table, webdavconfig.FieldID, selector),
			sqlgraph.To(storage.Table, storage.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, webdavconfig.StorageTable, webdavconfig.StorageColumn),
		)
		fromU = sqlgraph.SetNeighbors(wdcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WebDAVConfig entity from the query.
// Returns a *NotFoundError when no WebDAVConfig was found.
func (wdcq *WebDAVConfigQuery) First(ctx context.Context) (*WebDAVConfig, error) {
	nodes, err := wdcq.Limit(1).All(setContextOp(ctx, wdcq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{webdavconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) FirstX(ctx context.Context) *WebDAVConfig {
	node, err := wdcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WebDAVConfig ID from the query.
// Returns a *NotFoundError when no WebDAVConfig ID was found.
func (wdcq *WebDAVConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wdcq.Limit(1).IDs(setContextOp(ctx, wdcq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{webdavconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := wdcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WebDAVConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WebDAVConfig entity is found.
// Returns a *NotFoundError when no WebDAVConfig entities are found.
func (wdcq *WebDAVConfigQuery) Only(ctx context.Context) (*WebDAVConfig, error) {
	nodes, err := wdcq.Limit(2).All(setContextOp(ctx, wdcq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{webdavconfig.Label}
	default:
		return nil, &NotSingularError{webdavconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) OnlyX(ctx context.Context) *WebDAVConfig {
	node, err := wdcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WebDAVConfig ID in the query.
// Returns a *NotSingularError when more than one WebDAVConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (wdcq *WebDAVConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wdcq.Limit(2).IDs(setContextOp(ctx, wdcq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{webdavconfig.Label}
	default:
		err = &NotSingularError{webdavconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := wdcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WebDAVConfigs.
func (wdcq *WebDAVConfigQuery) All(ctx context.Context) ([]*WebDAVConfig, error) {
	ctx = setContextOp(ctx, wdcq.ctx, ent.OpQueryAll)
	if err := wdcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WebDAVConfig, *WebDAVConfigQuery]()
	return withInterceptors[[]*WebDAVConfig](ctx, wdcq, qr, wdcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) AllX(ctx context.Context) []*WebDAVConfig {
	nodes, err := wdcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WebDAVConfig IDs.
func (wdcq *WebDAVConfigQuery) IDs(ctx context.Context) (ids []int, err error) {
	if wdcq.ctx.Unique == nil && wdcq.path != nil {
		wdcq.Unique(true)
	}
	ctx = setContextOp(ctx, wdcq.ctx, ent.OpQueryIDs)
	if err = wdcq.Select(webdavconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := wdcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wdcq *WebDAVConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, wdcq.ctx, ent.OpQueryCount)
	if err := wdcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, wdcq, querierCount[*WebDAVConfigQuery](), wdcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) CountX(ctx context.Context) int {
	count, err := wdcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wdcq *WebDAVConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, wdcq.ctx, ent.OpQueryExist)
	switch _, err := wdcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (wdcq *WebDAVConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := wdcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WebDAVConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wdcq *WebDAVConfigQuery) Clone() *WebDAVConfigQuery {
	if wdcq == nil {
		return nil
	}
	return &WebDAVConfigQuery{
		config:      wdcq.config,
		ctx:         wdcq.ctx.Clone(),
		order:       append([]webdavconfig.OrderOption{}, wdcq.order...),
		inters:      append([]Interceptor{}, wdcq.inters...),
		predicates:  append([]predicate.WebDAVConfig{}, wdcq.predicates...),
		withStorage: wdcq.withStorage.Clone(),
		// clone intermediate query.
		sql:  wdcq.sql.Clone(),
		path: wdcq.path,
	}
}

// WithStorage tells the query-builder to eager-load the nodes that are connected to
// the "storage" edge. The optional arguments are used to configure the query builder of the edge.
func (wdcq *WebDAVConfigQuery) WithStorage(opts ...func(*StorageQuery)) *WebDAVConfigQuery {
	query := (&StorageClient{config: wdcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	wdcq.withStorage = query
	return wdcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WebDAVConfig.Query().
//		GroupBy(webdavconfig.FieldURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wdcq *WebDAVConfigQuery) GroupBy(field string, fields ...string) *WebDAVConfigGroupBy {
	wdcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WebDAVConfigGroupBy{build: wdcq}
	grbuild.flds = &wdcq.ctx.Fields
	grbuild.label = webdavconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URL string `json:"url,omitempty"`
//	}
//
//	client.WebDAVConfig.Query().
//		Select(webdavconfig.FieldURL).
//		Scan(ctx, &v)
func (wdcq *WebDAVConfigQuery) Select(fields ...string) *WebDAVConfigSelect {
	wdcq.ctx.Fields = append(wdcq.ctx.Fields, fields...)
	sbuild := &WebDAVConfigSelect{WebDAVConfigQuery: wdcq}
	sbuild.label = webdavconfig.Label
	sbuild.flds, sbuild.scan = &wdcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WebDAVConfigSelect configured with the given aggregations.
func (wdcq *WebDAVConfigQuery) Aggregate(fns ...AggregateFunc) *WebDAVConfigSelect {
	return wdcq.Select().Aggregate(fns...)
}

func (wdcq *WebDAVConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range wdcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, wdcq); err != nil {
				return err
			}
		}
	}
	for _, f := range wdcq.ctx.Fields {
		if !webdavconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wdcq.path != nil {
		prev, err := wdcq.path(ctx)
		if err != nil {
			return err
		}
		wdcq.sql = prev
	}
	return nil
}

func (wdcq *WebDAVConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WebDAVConfig, error) {
	var (
		nodes       = []*WebDAVConfig{}
		withFKs     = wdcq.withFKs
		_spec       = wdcq.querySpec()
		loadedTypes = [1]bool{
			wdcq.withStorage != nil,
		}
	)
	if wdcq.withStorage != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, webdavconfig.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WebDAVConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WebDAVConfig{config: wdcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, wdcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := wdcq.withStorage; query != nil {
		if err := wdcq.loadStorage(ctx, query, nodes, nil,
			func(n *WebDAVConfig, e *Storage) { n.Edges.Storage = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (wdcq *WebDAVConfigQuery) loadStorage(ctx context.Context, query *StorageQuery, nodes []*WebDAVConfig, init func(*WebDAVConfig), assign func(*WebDAVConfig, *Storage)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*WebDAVConfig)
	for i := range nodes {
		if nodes[i].storage_webdav_config == nil {
			continue
		}
		fk := *nodes[i].storage_webdav_config
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(storage.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "storage_webdav_config" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (wdcq *WebDAVConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wdcq.querySpec()
	_spec.Node.Columns = wdcq.ctx.Fields
	if len(wdcq.ctx.Fields) > 0 {
		_spec.Unique = wdcq.ctx.Unique != nil && *wdcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, wdcq.driver, _spec)
}

func (wdcq *WebDAVConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(webdavconfig.Table, webdavconfig.Columns, sqlgraph.NewFieldSpec(webdavconfig.FieldID, field.TypeInt))
	_spec.From = wdcq.sql
	if unique := wdcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if wdcq.path != nil {
		_spec.Unique = true
	}
	if fields := wdcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webdavconfig.FieldID)
		for i := range fields {
			if fields[i] != webdavconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wdcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wdcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wdcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wdcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wdcq *WebDAVConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wdcq.driver.Dialect())
	t1 := builder.Table(webdavconfig.Table)
	columns := wdcq.ctx.Fields
	if len(columns) == 0 {
		columns = webdavconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wdcq.sql != nil {
		selector = wdcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wdcq.ctx.Unique != nil && *wdcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range wdcq.predicates {
		p(selector)
	}
	for _, p := range wdcq.order {
		p(selector)
	}
	if offset := wdcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wdcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WebDAVConfigGroupBy is the group-by builder for WebDAVConfig entities.
type WebDAVConfigGroupBy struct {
	selector
	build *WebDAVConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wdcgb *WebDAVConfigGroupBy) Aggregate(fns ...AggregateFunc) *WebDAVConfigGroupBy {
	wdcgb.fns = append(wdcgb.fns, fns...)
	return wdcgb
}

// Scan applies the selector query and scans the result into the given value.
func (wdcgb *WebDAVConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wdcgb.build.ctx, ent.OpQueryGroupBy)
	if err := wdcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebDAVConfigQuery, *WebDAVConfigGroupBy](ctx, wdcgb.build, wdcgb, wdcgb.build.inters, v)
}

func (wdcgb *WebDAVConfigGroupBy) sqlScan(ctx context.Context, root *WebDAVConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(wdcgb.fns))
	for _, fn := range wdcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*wdcgb.flds)+len(wdcgb.fns))
		for _, f := range *wdcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*wdcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wdcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WebDAVConfigSelect is the builder for selecting fields of WebDAVConfig entities.
type WebDAVConfigSelect struct {
	*WebDAVConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (wdcs *WebDAVConfigSelect) Aggregate(fns ...AggregateFunc) *WebDAVConfigSelect {
	wdcs.fns = append(wdcs.fns, fns...)
	return wdcs
}

// Scan applies the selector query and scans the result into the given value.
func (wdcs *WebDAVConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, wdcs.ctx, ent.OpQuerySelect)
	if err := wdcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebDAVConfigQuery, *WebDAVConfigSelect](ctx, wdcs.WebDAVConfigQuery, wdcs, wdcs.inters, v)
}

func (wdcs *WebDAVConfigSelect) sqlScan(ctx context.Context, root *WebDAVConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(wdcs.fns))
	for _, fn := range wdcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*wdcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wdcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
