// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Storage is the predicate function for storage builders.
type Storage func(*sql.Selector)

// SyncJob is the predicate function for syncjob builders.
type SyncJob func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
